<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ClassRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return auth()->user()->hasAnyRole(['super-admin', 'admin', 'staff']);
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        $classId = $this->route('class')?->id;

        $rules = [
            'name' => 'required|string|max:255',
            // Code is now always auto-generated by ClassService - no validation needed
            'subject_id' => 'required|exists:subjects,id',
            'teacher_id' => 'nullable|exists:teachers,id',
            'type' => 'required|in:online,offline',
            // CHANGED: was 'nullable|string|max:50' → now FK validation
            'grade_level_id' => 'nullable|exists:grade_levels,id',
            'capacity' => 'required|integer|min:1|max:100',
            'price' => 'required|numeric|min:0|max:99999.99',
            'description' => 'nullable|string|max:2000',
            'location' => 'nullable|string|max:255',
            'meeting_link' => 'nullable|url|max:500',
            'status' => 'required|in:active,inactive,full',
        ];

        // Location is required for offline classes
        if ($this->input('type') === 'offline') {
            $rules['location'] = 'required|string|max:255';
        }

        // Meeting link is required for online classes
        if ($this->input('type') === 'online') {
            $rules['meeting_link'] = 'required|url|max:500';
        }

        // On update, ensure capacity is not less than current enrollment
        if ($this->isMethod('PUT') || $this->isMethod('PATCH')) {
            $class = $this->route('class');
            if ($class && $this->input('capacity') < $class->current_enrollment) {
                $rules['capacity'] = [
                    'required',
                    'integer',
                    'min:' . $class->current_enrollment,
                    'max:100',
                ];
            }
        }

        return $rules;
    }

    /**
     * Get custom messages for validator errors.
     */
    public function messages(): array
    {
        return [
            'name.required' => 'Class name is required.',
            'name.max' => 'Class name cannot exceed 255 characters.',
            'subject_id.required' => 'Please select a subject.',
            'subject_id.exists' => 'Selected subject does not exist.',
            'teacher_id.exists' => 'Selected teacher does not exist.',
            'type.required' => 'Class type is required.',
            'type.in' => 'Class type must be either online or offline.',
            // CHANGED: updated message for FK validation
            'grade_level_id.exists' => 'Selected grade level does not exist.',
            'capacity.required' => 'Class capacity is required.',
            'capacity.integer' => 'Capacity must be a whole number.',
            'capacity.min' => 'Capacity must be at least :min.',
            'capacity.max' => 'Capacity cannot exceed 100 students.',
            'price.required' => 'Class price is required.',
            'price.numeric' => 'Price must be a valid number.',
            'price.min' => 'Price cannot be negative.',
            'price.max' => 'Price cannot exceed RM 99,999.99.',
            'description.max' => 'Description cannot exceed 2000 characters.',
            'location.required' => 'Location is required for offline classes.',
            'location.max' => 'Location cannot exceed 255 characters.',
            'meeting_link.required' => 'Meeting link is required for online classes.',
            'meeting_link.url' => 'Please enter a valid URL for the meeting link.',
            'meeting_link.max' => 'Meeting link cannot exceed 500 characters.',
            'status.required' => 'Status is required.',
            'status.in' => 'Invalid status selected.',
        ];
    }

    /**
     * Get custom attributes for validator errors.
     */
    public function attributes(): array
    {
        return [
            'name' => 'class name',
            'subject_id' => 'subject',
            'teacher_id' => 'teacher',
            'type' => 'class type',
            'grade_level_id' => 'grade level',   // CHANGED: was 'grade_level'
            'capacity' => 'class capacity',
            'price' => 'class price',
            'description' => 'description',
            'location' => 'location',
            'meeting_link' => 'meeting link',
            'status' => 'status',
        ];
    }

    /**
     * Prepare the data for validation.
     */
    protected function prepareForValidation(): void
    {
        // Ensure capacity is an integer
        if ($this->has('capacity')) {
            $this->merge(['capacity' => (int) $this->input('capacity')]);
        }

        // Ensure price is properly formatted
        if ($this->has('price') && $this->input('price') !== '') {
            $this->merge(['price' => (float) $this->input('price')]);
        }

        // Remove code field from input - it's always auto-generated by ClassService
        $this->request->remove('code');
    }
}
